SETTING_HA_URL = "ha_url"
SETTING_HA_TOKEN = "ha_token"
SETTING_HA_TEMP_SENSOR = "ha_temp_sensor"
SETTING_HA_HEATER_SWITCH = "ha_heater_switch"

SETTING_TRIGGER = "trigger"
SETTING_OFF_CONDITION = "off_condition"

SETTING_TEMP_MODE = "temp_mode"
SETTING_TARGET_TEMP = "target_temp"
SETTING_OFFSET_VALUE = "offset_value"
SETTING_OFFSET_PERCENT = "offset_percent"
SETTING_OFFSET_TYPE = "offset_type"

SETTING_HA_VERIFY_SSL = "ha_verify_ssl"

SETTING_HYSTERESIS = "hysteresis"
SETTING_UPDATE_INTERVAL = "update_interval"
SETTING_TEMP_TIMEOUT = "temp_unavailable_timeout"

SETTING_HEATER_MODE = "heater_mode"
SETTING_THERMAL_RUNAWAY_TEMP = "thermal_runaway_temp"
SETTING_THERMAL_RUNAWAY_ENABLED = "thermal_runaway_enabled"
SETTING_THERMAL_RUNAWAY_TRIGGERED = "thermal_runaway_triggered"

HEATER_MODE_AUTO = "auto"
HEATER_MODE_MANUAL_ON = "manual_on"
HEATER_MODE_MANUAL_OFF = "manual_off"

TRIGGER_BED_SET = "bed_set"
TRIGGER_PRINT_RUNNING = "print_running"
TRIGGER_THERMOSTAT = "thermostat"

OFF_CONDITION_BED_UNSET = "bed_unset"
OFF_CONDITION_PRINT_IDLE = "print_idle"
OFF_CONDITION_THERMOSTAT = "thermostat"

TEMP_MODE_DIRECT = "direct"
TEMP_MODE_BED_OFFSET = "bed_offset"

OFFSET_TYPE_RAW = "raw"
OFFSET_TYPE_PERCENT = "percent"

TRIGGER_OPTIONS = [TRIGGER_BED_SET, TRIGGER_PRINT_RUNNING, TRIGGER_THERMOSTAT]
OFF_CONDITION_OPTIONS = [OFF_CONDITION_BED_UNSET, OFF_CONDITION_PRINT_IDLE, OFF_CONDITION_THERMOSTAT]
TEMP_MODE_OPTIONS = [TEMP_MODE_DIRECT, TEMP_MODE_BED_OFFSET]
OFFSET_TYPE_OPTIONS = [OFFSET_TYPE_RAW, OFFSET_TYPE_PERCENT]
HEATER_MODE_OPTIONS = [HEATER_MODE_AUTO, HEATER_MODE_MANUAL_ON, HEATER_MODE_MANUAL_OFF]

PRINT_STATES = {"printing", "pausing", "cancelling", "paused", "ready", "error"}
PRINT_ACTIVE_STATES = {"printing", "pausing", "cancelling"}